config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'

  root 'home#index'
  resources :pictures
  post '/like', to: 'like#like', as: 'like_picture'
  get '/tags/:tag_id', to: 'home#index', as: 'picture_by_tag'
  get '/users', to: 'home#myPicture', as: 'my_picture'
  get '/users/:user_pseudo-:user_id', to: 'home#index', as: 'picture_by_user'
  get '/categories/:category_id', to: 'home#index', as: 'picture_by_cayegory'
  get '/search', to: 'home#index', as: 'search_picture'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :picures
end

app/models/linkpicturetag.rb
class Linkpicturetag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :linkpicturetags
  has_many :tags, through: :linkpicturetags
  belongs_to :category
  belongs_to :user

  has_many :likes
  attr_accessor :liked
  acts_as_votable

  def self.search(args)
    out = []
    @text_search = args[:search]
    if @text_search.first == "#"
      @text_search[0] = ''
      out = Picture.joins(:linkpicturetags).joins(:tags).where(["UPPER(tags.name) LIKE :query", query: "%#{@text_search.capitalize}%"])
    else
      out = Picture.joins(:user).where(["UPPER(users.pseudo) LIKE :query", query: "%#{@text_search.upcase}%"])
    end
    return out.limit(6)
  end

  def self.filter(args)
    out = []
    if args[:search].present?
        out = search(args)
    elsif args[:category_id].present?
        out = Picture.where("category_id = ?", args[:category_id])
    elsif args[:tag_id].present?
        out = Picture.joins(:linkpicturetags).where("linkpicturetags.tag_id = ?", args[:tag_id])
    elsif args[:user_id].present?
        out = Picture.where("user_id = ?", args[:user_id])
    else
        out = Picture.all
    end

    if args[:last_id].present?
        out = out.where("id < ?", args[:last_id])
    end

    return out.order('pictures.id DESC').limit(6)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :linkpicturetags
  has_many :pictures, through: :linkpicturetags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures

  has_many :likes
  acts_as_voter

  def switchLike(picture_id)
    result = {picture_id: picture_id, sucess: false}
    image = Picture.find(picture_id)
    if voted_for? image
      unlike image
      result[:liked] = false
    else
      likes image
      result[:liked] = true
    end
    result[:success] =  true
    result[:number_like] = image.get_likes.size

    ActionCable.server.broadcast "like_channel", type: 'stats-like', picture_id: picture_id, likes: image.get_likes.size

    return result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo, :email, :password, :password_confirmation])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pictures = Picture.filter(params);


    if request.xhr?
      data = render_to_string partial: "home/picture"
      last_id = 0
      if @pictures.last
        last_id = @pictures.last.id
      end
      render json: {data: data, last_id: last_id}.to_json
    end
  end

  def myPicture
    if current_user
      @pictures = Picture.filter(user_id: current_user.id);
      render :index
    else
      redirect_to root_path
    end
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def like
    data = current_user.switchLike(params[:picture_id])
    render json: data.to_json
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to my_picture_path }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @picture = Picture.find(params[:picture_id])
  end

  private

    def picture_params
      params
        .require(:picture)
        .permit(
          :picture,
          :category_id,
          tag_ids: [])
        .merge(user_id: current_user.id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def heart(color, size)
    out= "<svg xmlns='http://www.w3.org/2000/svg' width='#{size}' height='#{size}' viewBox='0 0 8 8' fill='#{color}'>
      <path d='M2 0c-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0 .55.23 1.04.59 1.41l3.41 3.41 3.41-3.41c.36-.36.59-.85.59-1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59z'
      transform='translate(0 1)'/>
    </svg>".html_safe
  end
end

app/views/home/_picture.html.haml
- @pictures.each do |picture|
  - if picture.picture.url
    .container-picture
      .tag{id: "image-#{picture.id}"}
        .container-fluid
          .row
            .col-xs-2
              - if user_signed_in?
                %a{href: '#', class: "like #{'liked' if current_user.voted_for? picture}", data: {do: 'like', id: picture.id}}
                  = heart('grey', 30)
              - else
                %a.my-account{href: new_user_session_path}
                  = heart('red', 30)
            .col-xs-1{id: "nb-like-#{picture.id}"}
              = picture.get_likes.size
            .col-xs-5
              - picture.tags.each do |tag|
                = link_to tag.name, picture_by_tag_path(tag.id)
            .col-xs-4
              = link_to "Postée par #{picture.user.pseudo}", picture_by_user_path(picture.user.pseudo, picture.user.id)

      %a{href: picture.picture.url, data: {lightbox: picture.category.name}}
        %img{src:picture.picture.url}

app/views/home/index.html.haml
- if @pictures.count > 0
  %section{id: 'photos'}
    =render partial: "picture"
  .container-fluid
    .row.text-center
      %a{href: "#", data: {do: 'more'}, id: "more-button"}
        %button.btn.btn-success
          Afficher plus
- else
  .alert.alert-danger.text-center
    Aucune image trouvée !

:javascript
  if ("#{@pictures.last}" != "#{nil}"){
    window.last = "#{@pictures.last.try(:id)}"
  }
  else{
    window.last = 0
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Listings
    = csrf_meta_tags
    %script{:crossorigin => "anonymous", :integrity => "sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=", :src => "https://code.jquery.com/jquery-3.2.1.min.js"}
    %link{:href => "https://fonts.googleapis.com/css?family=Dosis", :rel => "stylesheet"}
    %link{:href => "//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css", :rel => "stylesheet"}/
    %link{:href => "//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body{:class => "#{params[:controller]}"}
    = render partial: '/shared/header'
    .container.content
      - if notice
        %p.notice.alert-info.text-center
          = notice
      - if alert
        %p.alert.alert-danger.text-center
          = alert
      = yield

      = render partial: '/shared/footer'

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

app/views/pictures/new.html.haml
.row
  .col-xs-8.col-xs-offset-2.well
    /*- if user_signed_in?*/
    = form_for @picture, class: 'form', html: {multipart: true} do |f|
      .form-group
        = f.label :picture, class: 'form-label required'
        = f.file_field :picture, class: 'form-control', required: true
      .form-group
        = f.label :category_id, class: 'form-label required'
        = f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}
      .form-group
        - Tag.all.each do |tag|
          %div.some{ :style => "width: 100px; display: inline-block;" }
            = check_box_tag 'picture[tag_ids][]', tag.id
            = tag.name
      .form-group
        = f.submit 'ajouter la photo', class: 'btn btn-primary center-block'

app/views/shared/_footer.html.haml
.container.footer.text-center
  %p LeRoiMerlin : Une passion, vos images ! - Une création de Thibault Buathier et Alaxandre Rosset - INGÉsup B3 une école d'Ynov Lyon

app/views/shared/_header.html.haml
-# .header
-#   .container-fluid.header
-#     .row
-#       .top
-#         .col-xs-3.text-center
-#           %h1.title
-#             %a{:href => root_path} LeRoiMerlin
-#         .col-xs-3
-#           - Category.all.each do |category|
-#             = link_to category.name, picture_by_cayegory_path(category.id), class: "link-category"
-#         .col-xs-3
-#           = form_tag(search_picture_path, method: "get") do
-#             = text_field_tag(:search)
-#         .col-xs-3.text-center
-#           - if user_signed_in?
-#             %a.logout{href: destroy_user_session_path, data: {method: 'delete'}}
-#               %button.btn.btn-success
-#                 Se deconnecer
-#             %a{href: new_picture_path}
-#               %button.btn.btn-success
-#                 Uploader une image
-#           - else
-#             %a.my-account{href: new_user_session_path}
-#               %button.btn.btn-success
-#                 Se connecter
-#         .clearfix
-#
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .col-xs-4
      %a.navbar-brand{href: root_path}
        LeRoiMerlin
      %ul.nav.navbar-nav
        - Category.all.each do |category|
          %li
            %a{href: picture_by_cayegory_path(category.id)}
              = category.name
    .col-xs-4
      %form.navbar-form.navbar-left{action: search_picture_path, method: "get", style: "width: 100%;"}
        %input.form-control{type: "text", name: "search", placeholder: "Rechercher...", style: "width: 100%;", value: "#{@text_search if @text_searchl}"}
    .col-xs-4.buttons-menu-top
      - if user_signed_in?
        %a.logout{href: destroy_user_session_path, data: {method: 'delete'}}
          %button.btn.btn-success.pull-right
            Se deconnecer
        %a{href: new_picture_path}
          %button.btn.btn-success.pull-right
            Uploader une image
      - else
        %a.my-account{href: new_user_session_path}
          %button.btn.btn-success.pull-right
            Se connecter